version: "3"

services:
  # PostgreSQL database
  postgres:
    image: postgres:14
    container_name: myapp_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-myapp}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Development API service
  api:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: myapp_api_dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-myapp}
      - DB_SSLMODE=disable
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRES_IN=24h
      - GIN_MODE=debug
    volumes:
      - .:/app
    networks:
      - myapp_network
    restart: unless-stopped

  # Production API service
  api-prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: myapp_api_prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-myapp}
      - DB_SSLMODE=disable
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - JWT_EXPIRES_IN=24h
      - GIN_MODE=release
    networks:
      - myapp_network
    restart: unless-stopped
    profiles:
      - prod

  # PgAdmin for development
  pgadmin:
    image: dpage/pgadmin4
    container_name: myapp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    networks:
      - myapp_network
    restart: unless-stopped

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_data:
