package routes

import (
	_ "myapp/docs" // docs is generated by Swag CLI

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
)

// SetupSwaggerRoutes sets up the Swagger UI routes
func SetupSwaggerRoutes(r chi.Router) {
	// Swagger UI
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // The url pointing to API definition
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	))
}
